# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: citizen-services-portal
metadata:
  template: citizen-services-portal@0.0.1

infra:
  provider: bicep
  path: infra
  module: main

pipeline:
  provider: github

services:
  mcp-ladbs:
    project: ./src/mcp-servers/ladbs
    language: py
    host: containerapp
    docker:
      path: ./Dockerfile
      context: .
      registry: aldelarcspcr.azurecr.io

